### ISSUE TITLE
Help With ESPHomeRoombaComponent

### ISSUE THREAD

**Issue by wes1993** [MatthewGCampbell/MatthewGCampbell#1]
Hello,
sorry if i write here but i can't find the issue in this repo:
https://github.com/MatthewGCampbell/ESPHomeRoombaComponent

I have compiled successfully but i can't set the MQTT i couldn't see the updated status:

![image](https://user-images.githubusercontent.com/52070589/146202678-6dd2f451-454a-4065-92e1-1f72fe576a76.png)

![image](https://user-images.githubusercontent.com/52070589/146202708-1898c7df-31f1-4746-bb48-3ffdbea25b07.png)

Could you help me please?

I have an ESP01S

Thanks a lot
Stefano

**Comment by MatthewGCampbell** [comment]
Just saw this now, do you still need help with this? I broke my Roomba and was working on trying to get it working, it seemed to not work at least back when I tested it. As I was messing with my vacuum I ended up ruining the main board so I can’t really help. I bought the s9 vacuum after mine broke.

**Comment by wes1993** [comment]
Hello @MatthewGCampbell,
Thanks a lot for your reply :)
No I have finally created a new project using Blynk framework but thanks really for you reply :)
